name: 'Cucumber Report to Annotations'
description: 'Create an annotation of the test run summary and also list first n failed tests as seporate annotations'
branding:
  icon: check-square
  color: green
inputs:
  access-token:
    description: "github token"
    required: true
  path:
    description: "glob to cucumber json files"
    required: true
    default: "**/cucumber-report.json"
  check-status-on-error:
    description: "the check status to use on cucumber error. Can be 'success', 'neutral' or 'failure'"
    required: true
    default: 'failure'
  check-status-on-undefined:
    description: "the check status to use on cucumber undefined steps. Can be 'success', 'neutral' or 'failure'"
    required: true
    default: 'success'
  check-status-on-pending:
    description: "the check status to use on cucumber pending steps. Can be 'success', 'neutral' or 'failure'"
    required: true
    default: 'success'
  annotation-status-on-error:
    description: "the annotation status on error. Can be 'notice', 'warning', 'failure'"
    require: true
    default: 'failure'
  annotation-status-on-undefined:
    description: "the annotation status on undefined steps. Can be 'notice', 'warning', 'failure'. if this property is not set, no annotation will be generated for undefined steps"
    require: false
  annotation-status-on-pending:
    description: "the annotation status on pending steps. Can be 'notice', 'warning', 'failure'. if this property is not set, no annotation will be generated for pending steps"
    require: false
  show-number-of-error-on-check-title:
    description: "if it is set to true, the number of errors will be indicated on the check title (visible on the pr check)"
    require: true
    default: 'true'
  number-of-test-error-to-fail-job:
    description: "indicate the number of test in error to fail the build. If the value is -1 this action will never fail the build."
    require: true
    default: -1
  name:
    description: "the name of the check"
    require: true
    default: 'Cucumber report'

runs:
  using: 'node16'
  main: 'dist/index.js'
