name: Tests JSOND

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ubuntu-action-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run cucumber-message || true
      - uses: ./
        name: "JSOND - full report"
        with:
          name: "full report"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.jsond"
      